In [138]:
import numpy as np

a = np.array([1,2,3,4])                               # 1 dim array
b = np.zeros(4)                                       # 1 dim array of zeroes
c = np.zeros(shape=(3,3))                             # 2 dim array of zeroes with shape (3,3)
d = np.ones(shape=(2,5,4))                            # 3 dim array of ones with shape (2,5)
e = np.eye(20)                                        # 2 dim array with shape (20,20) (identity matrix)
f = np.array([[1,0,2], [2,3,6]])                      # 2 dim array with shape(2,3)
g = np.random.randint(low=-3, high=25, size=(3,7))    # 2 dim array with shape(3,7) populated with random integers
h = np.empty(shape=(10,4))

In [169]:
rand  = np.random.randint(1, 10, (4, 5))
rand = rand.reshape(2, 5, 2)
print(rand)



[[[4 4]
  [3 1]
  [8 6]
  [5 3]
  [3 5]]

 [[7 5]
  [4 7]
  [9 2]
  [1 7]
  [3 8]]]


In [181]:
m = rand.sum(axis=0)
print(m)

[[11  9]
 [ 7  8]
 [17  8]
 [ 6 10]
 [ 6 13]]


In [182]:
eye = np.eye(5)
print(eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [205]:
m1 = np.array(range(1, 9)).reshape(-1, 4)
m2 = np.array(range(9, 17)).reshape(-1, 4)
m3 = np.array([1,2,3,4])

# print(m1, m2)
x = np.concatenate((m1, m2), axis=0)
print(m1)
print(m2)

print(x)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
