In [2]:
import numpy as np

a = np.array([1,2,3,4])                               # 1 dim array
b = np.zeros(4)                                       # 1 dim array of zeroes
c = np.zeros(shape=(3,3))                             # 2 dim array of zeroes with shape (3,3)
d = np.ones(shape=(2,5,4))                            # 3 dim array of ones with shape (2,5)
e = np.eye(20)                                        # 2 dim array with shape (20,20) (identity matrix)
f = np.array([[1,0,2], [2,3,6]])                      # 2 dim array with shape(2,3)
g = np.random.randint(low=-3, high=25, size=(3,7))    # 2 dim array with shape(3,7) populated with random integers
h = np.empty(shape=(10,4))

In [3]:
rand  = np.random.randint(1, 10, (4, 5))
rand = rand.reshape(2, 5, 2)
print(rand)



[[[1 8]
  [8 1]
  [1 8]
  [3 8]
  [3 7]]

 [[2 8]
  [6 2]
  [2 8]
  [7 5]
  [6 4]]]


In [4]:
m = rand.sum(axis=0)
print(m)

[[ 3 16]
 [14  3]
 [ 3 16]
 [10 13]
 [ 9 11]]


In [5]:
eye = np.eye(5)
print(eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [6]:
m1 = np.array(range(1, 9)).reshape(-1, 4)
m2 = np.array(range(9, 17)).reshape(-1, 4)
m3 = np.array([1,2,3,4])

# print(m1, m2)
x = np.concatenate((m1, m2), axis=0)
print(m1)
print(m2)

print(x)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [33]:
a = np.full((4,4), 6)
b = np.full(4, 10)
c = np.concatenate((a,b.reshape(-1,1)), axis=1)

print(c)

[[ 6  6  6  6 10]
 [ 6  6  6  6 10]
 [ 6  6  6  6 10]
 [ 6  6  6  6 10]]


In [98]:
rand = np.random.randint(1, 11, (8,8))
result = np.split(rand, [3, 5])

print(rand, *result, sep="\n\n")
# print(rand)

[[ 3  3  4  1  3  2  6 10]
 [ 4  3  2  3  9 10  7  7]
 [ 9  3  3  8 10  3  5 10]
 [ 4  8  7  6  9 10  5 10]
 [ 6  8  3  1  6  3  6  3]
 [ 8  8 10  3  5  4  3  9]
 [ 4  4  9  3  1  9  3 10]
 [ 5  3 10  6  9  6  2  1]]

[[ 3  3  4  1  3  2  6 10]
 [ 4  3  2  3  9 10  7  7]
 [ 9  3  3  8 10  3  5 10]]

[[ 4  8  7  6  9 10  5 10]
 [ 6  8  3  1  6  3  6  3]]

[[ 8  8 10  3  5  4  3  9]
 [ 4  4  9  3  1  9  3 10]
 [ 5  3 10  6  9  6  2  1]]


In [126]:
# Dot Product

a = np.array(range(1, 17)).reshape((4,4))
a, b = np.split(a, 2)
b = b.reshape(-1, 2)
print(a)
print(b)

dot1 = np.dot(a,b)
dot2 = a@b
dot3 = np.matmul(b,a)


print(dot1, dot2, dot3, sep="\n\n")

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]
[[130 140]
 [322 348]]

[[130 140]
 [322 348]]

[[ 59  78  97 116]
 [ 71  94 117 140]
 [ 83 110 137 164]
 [ 95 126 157 188]]
